export const UPDATE_DATES = 'UPDATE_DATES';
export const REMOVE_DATE = 'REMOVE_DATE';
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';
export const ADD_DATE = 'ADD_DATE';
export const LOADING = 'LOADING';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
